# Generated by Django 2.1.3 on 2019-03-02 15:33

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='REPotentialAreas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('area_params', django.contrib.postgres.fields.jsonb.JSONField(unique=True)),
                ('mun_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3035)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_user_scenario', models.BooleanField(default=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(unique=True)),
                ('re_potential_areas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stemp_abw.REPotentialAreas')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationResults',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stemp_abw.Scenario')),
            ],
        ),
    ]
