# Generated by Django 2.1.1 on 2018-09-20 07:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0002_auto_20180912_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsmPowerGen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=3035)),
                ('subst_id', models.IntegerField()),
                ('la_id', models.IntegerField()),
                ('osm_id', models.IntegerField()),
            ],
        ),
    ]
