# Generated by Django 2.1.3 on 2019-03-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0002_repotentialareas_scenario_simulationresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
