# Generated by Django 2.1.1 on 2018-09-20 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0003_osmpowergen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osmpowergen',
            name='la_id',
        ),
    ]
