# Generated by Django 2.1.1 on 2018-09-20 07:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0004_remove_osmpowergen_la_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmpowergen',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=3035),
        ),
    ]
