# Generated by Django 2.1.3 on 2019-03-08 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0004_auto_20190308_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='data_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
