# Generated by Django 2.1.3 on 2019-03-13 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0005_scenario_data_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='data_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
