# Generated by Django 2.1.3 on 2019-03-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0009_auto_20190321_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='mundata',
            name='reg_prio_area_wec_area',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mundata',
            name='reg_prio_area_wec_count',
            field=models.IntegerField(null=True),
        ),
    ]
