# Generated by Django 2.1.1 on 2018-09-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0009_osmpowergen_geom2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osmpowergen',
            name='geom',
        ),
    ]
