# Generated by Django 2.1.1 on 2018-09-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0010_remove_osmpowergen_geom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osmpowergen',
            old_name='geom2',
            new_name='geom',
        ),
    ]
