# Generated by Django 2.1.3 on 2019-03-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0011_repoweringscenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='repowering_scenario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='stemp_abw.RepoweringScenario'),
            preserve_default=False,
        ),
    ]
