# Generated by Django 2.1.3 on 2019-03-22 16:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0013_auto_20190322_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repoweringscenario',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
