# Generated by Django 2.1.1 on 2018-09-20 09:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0013_remove_osmpowergen_geom2'),
    ]

    operations = [
        migrations.CreateModel(
            name='RpAbwBound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=3035)),
            ],
        ),
    ]
