# Generated by Django 2.1.3 on 2019-03-25 23:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0014_auto_20190322_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repotentialareas',
            name='area_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='repotentialareas',
            name='mun_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
