# Generated by Django 2.1.3 on 2019-03-25 23:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0015_auto_20190326_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repotentialareas',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3035),
        ),
    ]
