# Generated by Django 2.1.1 on 2018-09-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0015_auto_20180920_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpabwbound',
            old_name='geom',
            new_name='geom2',
        ),
    ]
