# Generated by Django 2.1.3 on 2019-03-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0016_auto_20190326_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='REPotentialAreas1',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.repotentialareas',),
        ),
        migrations.CreateModel(
            name='REPotentialAreas2',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.repotentialareas',),
        ),
        migrations.CreateModel(
            name='REPotentialAreas3',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.repotentialareas',),
        ),
        migrations.CreateModel(
            name='REPotentialAreas4',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.repotentialareas',),
        ),
        migrations.CreateModel(
            name='REPotentialAreas5',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.repotentialareas',),
        ),
        migrations.CreateModel(
            name='REPotentialAreas6',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.repotentialareas',),
        ),
    ]
