# Generated by Django 2.1.1 on 2018-09-20 09:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0016_auto_20180920_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpabwbound',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326),
        ),
    ]
