# Generated by Django 2.1.3 on 2019-05-10 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0017_repotentialareas1_repotentialareas2_repotentialareas3_repotentialareas4_repotentialareas5_repotentia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='REPotentialAreas1',
        ),
        migrations.DeleteModel(
            name='REPotentialAreas2',
        ),
        migrations.DeleteModel(
            name='REPotentialAreas3',
        ),
        migrations.DeleteModel(
            name='REPotentialAreas4',
        ),
        migrations.DeleteModel(
            name='REPotentialAreas5',
        ),
        migrations.DeleteModel(
            name='REPotentialAreas6',
        ),
        migrations.RemoveField(
            model_name='simulationresults',
            name='scenario',
        ),
        migrations.AddField(
            model_name='scenario',
            name='results',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stemp_abw.SimulationResults'),
        ),
    ]
