# Generated by Django 2.1.1 on 2018-09-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0017_rpabwbound_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpabwbound',
            name='geom2',
        ),
    ]
