# Generated by Django 2.1.3 on 2019-05-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0018_auto_20190510_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegMunPopDensityResult',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.regmun',),
        ),
        migrations.CreateModel(
            name='RegMunPopResult',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.regmun',),
        ),
    ]
