# Generated by Django 2.1.1 on 2018-10-09 06:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0018_remove_rpabwbound_geom2'),
    ]

    operations = [
        migrations.CreateModel(
            name='RpAbwRegionPrioAreaResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('bezeich_2', models.CharField(max_length=254)),
                ('bezeich_3', models.CharField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
