# Generated by Django 2.1.1 on 2018-10-09 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0019_rpabwregionprioarearesource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RpAbwRegionPrioAreaResource',
            new_name='RegionPrioAreaRes',
        ),
    ]
