# Generated by Django 2.1.3 on 2019-06-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0019_regmunpopdensityresult_regmunpopresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegMunEnergyReElDemShareResult',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.regmungenenergyre', 'stemp_abw.regmundemelenergy'),
        ),
    ]
