# Generated by Django 2.1.1 on 2018-10-09 06:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0020_auto_20181009_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionprioareares',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3035),
        ),
    ]
