# Generated by Django 2.1.3 on 2019-06-05 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0020_regmunenergyreeldemshareresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegMunGenEnergyReResult',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.regmun',),
        ),
    ]
