# Generated by Django 2.1.3 on 2019-06-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0021_regmungenenergyreresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegMunGenEnergyReDensityResult',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.regmungenenergyre',),
        ),
    ]
