# Generated by Django 2.1.1 on 2018-10-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0022_regionwaterprotareas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegionPrioAreaRes',
            new_name='RegPrioAreaRes',
        ),
        migrations.RenameModel(
            old_name='RegionWaterProtAreas',
            new_name='RegWaterProtAreas',
        ),
    ]
