# Generated by Django 2.1.1 on 2018-10-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0023_auto_20181009_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regwaterprotareas',
            name='amtsblatt',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='regwaterprotareas',
            name='erfassungs',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='regwaterprotareas',
            name='gebietsnam',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='regwaterprotareas',
            name='gebietsnum',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='regwaterprotareas',
            name='rechtsgrun',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='regwaterprotareas',
            name='schutzzone',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
