# Generated by Django 2.1.1 on 2018-10-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0025_auto_20181009_0855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegWaterProtAreas',
            new_name='RegWaterProtArea',
        ),
    ]
