# Generated by Django 2.1.3 on 2019-06-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0028_regmundemthenergyresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegMunDemThEnergyPerCapitaResult',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.regmundemthenergy',),
        ),
    ]
