# Generated by Django 2.1.3 on 2019-06-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0029_regmundemthenergypercapitaresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegMunPopDensityResult',
        ),
        migrations.DeleteModel(
            name='RegMunPopResult',
        ),
    ]
