# Generated by Django 2.1.1 on 2018-10-09 08:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0030_regnatureprotarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegLandscProtArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3035)),
                ('gebietsnam', models.CharField(max_length=254, null=True)),
                ('gebietsnum', models.CharField(max_length=254, null=True)),
                ('rechtsgrun', models.CharField(max_length=254, null=True)),
                ('erfassungs', models.CharField(max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
