# Generated by Django 2.1.3 on 2019-06-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0030_auto_20190605_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegMunEnergyReElDemShareResultDelta',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.regmun',),
        ),
    ]
