# Generated by Django 2.1.3 on 2019-06-06 10:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0031_regmunenergyreeldemshareresultdelta'),
    ]

    operations = [
        migrations.AddField(
            model_name='regmun',
            name='geom_centroid',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=3035),
        ),
    ]
