# Generated by Django 2.1.3 on 2019-06-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0032_regmun_geom_centroid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegMunGenEnergyReDeltaResult',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.regmun',),
        ),
    ]
