# Generated by Django 2.1.3 on 2019-06-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0033_regmungenenergyredeltaresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegMunEnergyReElDemShareResultDelta',
        ),
    ]
