# Generated by Django 2.1.1 on 2018-10-09 22:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0034_regprioareafloodprot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegMun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3035)),
                ('rs', models.CharField(max_length=254, null=True)),
                ('ags', models.CharField(max_length=254, null=True)),
                ('gen', models.CharField(max_length=254, null=True)),
                ('bez', models.CharField(max_length=254, null=True)),
                ('nuts', models.CharField(max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
