# Generated by Django 2.1.3 on 2019-06-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0035_auto_20190606_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegMunDemElEnergyDeltaResult',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.regmun',),
        ),
        migrations.CreateModel(
            name='RegMunDemElEnergyPerCapitaDeltaResult',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.regmun',),
        ),
        migrations.CreateModel(
            name='RegMunEnergyReElDemShareDeltaResult',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.regmun',),
        ),
        migrations.CreateModel(
            name='RegMunGenCapReDeltaResult',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.regmun',),
        ),
        migrations.CreateModel(
            name='RegMunGenCapReDensityDeltaResult',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.regmun',),
        ),
        migrations.CreateModel(
            name='RegMunGenCountWindDensityDeltaResult',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.regmun',),
        ),
        migrations.CreateModel(
            name='RegMunGenEnergyReDensityDeltaResult',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.regmun',),
        ),
    ]
