# Generated by Django 2.1.3 on 2019-06-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0036_regmundemelenergydeltaresult_regmundemelenergypercapitadeltaresult_regmunenergyreeldemsharedeltaresu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultLayerModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('stemp_abw.regmun',),
        ),
        migrations.AddField(
            model_name='feedints',
            name='conventional',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
