# Generated by Django 2.1.3 on 2019-06-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0037_auto_20190616_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedints',
            name='bio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
