# Generated by Django 2.1.3 on 2019-06-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0038_feedints_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mundata',
            name='gen_el_energy_bio',
            field=models.FloatField(null=True),
        ),
    ]
