# Generated by Django 2.1.1 on 2018-10-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0039_regprioareacult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regprioareacult',
            name='bemerkunge',
        ),
    ]
