# Generated by Django 2.1.3 on 2019-06-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0039_mundata_gen_el_energy_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mundata',
            name='gen_el_energy_conventional',
            field=models.FloatField(null=True),
        ),
    ]
