# Generated by Django 2.1.3 on 2019-06-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0040_mundata_gen_el_energy_conventional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mundata',
            name='gen_capacity_combined_cycle',
        ),
        migrations.RemoveField(
            model_name='mundata',
            name='gen_capacity_steam_turbine',
        ),
        migrations.RemoveField(
            model_name='mundata',
            name='gen_count_combined_cycle',
        ),
        migrations.RemoveField(
            model_name='mundata',
            name='gen_count_steam_turbine',
        ),
        migrations.AddField(
            model_name='mundata',
            name='gen_capacity_conventional_large',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mundata',
            name='gen_capacity_conventional_small',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mundata',
            name='gen_count_conventional_large',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mundata',
            name='gen_count_conventional_small',
            field=models.FloatField(null=True),
        ),
    ]
