# Generated by Django 2.1.3 on 2019-06-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0042_regsurfacewater'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegSurfaceWater',
        ),
    ]
