# Generated by Django 2.1.3 on 2019-06-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0044_regsurfacewater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regprioareares',
            name='bezeich_3',
        ),
        migrations.AddField(
            model_name='regbioreserve',
            name='erfassungs',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regbioreserve',
            name='gebietsnam',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regbioreserve',
            name='gebietsnum',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regbioreserve',
            name='info_konta',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regbioreserve',
            name='rechtsgrun',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regbioreserve',
            name='schutzzone',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reglandscprotarea',
            name='erfassungs',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reglandscprotarea',
            name='gebietsnam',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reglandscprotarea',
            name='gebietsnum',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reglandscprotarea',
            name='info_konta',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reglandscprotarea',
            name='rechtsgrun',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regnaturemonum',
            name='erfassungs',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regnaturemonum',
            name='gebietsnam',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regnaturemonum',
            name='gebietsnum',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regnaturemonum',
            name='info_konta',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regnaturemonum',
            name='rechtsgrun',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regnaturepark',
            name='erfassungs',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regnaturepark',
            name='gebietsnam',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regnaturepark',
            name='gebietsnum',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regnaturepark',
            name='info_konta',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regnaturepark',
            name='rechtsgrun',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regprioareaagri',
            name='bezeich_2',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regprioareanature',
            name='bezeich_2',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regprioareawater',
            name='bezeich_2',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regretentareaagri',
            name='bezeich_2',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regretentareaecosys',
            name='bezeich_2',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
