# Generated by Django 2.1.1 on 2018-11-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0044_regdeadzonehard_regdeadzonesoft'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegLandscProtArea',
            new_name='RegLandscProtAreaParts',
        ),
    ]
