# Generated by Django 2.1.1 on 2018-11-26 17:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0045_auto_20181126_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegBioReserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3035)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegFFHProtAreaB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3035)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegInfrasAviation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3035)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegInfrasHvgrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3035)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegInfrasRailway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3035)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegInfrasRoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3035)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegLandscProtArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3035)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegNatureMonum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3035)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegNaturePark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3035)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegPrioAreaAgri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3035)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegPrioAreaNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3035)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegPrioAreaWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3035)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegRetentAreaAgri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3035)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegRetentAreaEcosys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3035)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
