# Generated by Django 2.2.3 on 2019-09-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0045_auto_20190624_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repoweringscenario',
            old_name='description',
            new_name='desc_de',
        ),
        migrations.RenameField(
            model_name='repoweringscenario',
            old_name='name',
            new_name='name_de',
        ),
    ]
