# Generated by Django 2.2.3 on 2019-09-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0046_auto_20190919_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='repoweringscenario',
            name='desc_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='repoweringscenario',
            name='name_en',
            field=models.CharField(default='x', max_length=50),
            preserve_default=False,
        ),
    ]
