# Generated by Django 2.2.3 on 2019-09-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0047_auto_20190919_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repoweringscenario',
            name='name_de',
            field=models.CharField(max_length=50),
        ),
    ]
