# Generated by Django 2.1.3 on 2019-01-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0047_auto_20190122_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regmun',
            name='id',
        ),
        migrations.RemoveField(
            model_name='regmun',
            name='pop_km2',
        ),
        migrations.RemoveField(
            model_name='regmun',
            name='rs',
        ),
        migrations.AlterField(
            model_name='regmun',
            name='ags',
            field=models.IntegerField(default=5, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
