# Generated by Django 2.1.3 on 2019-01-21 12:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0048_auto_20190121_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regmun',
            name='bez',
        ),
        migrations.RemoveField(
            model_name='regmun',
            name='nuts',
        ),
        migrations.AlterField(
            model_name='regmun',
            name='gen',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regmun',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=3035),
            preserve_default=False,
        ),
    ]
