# Generated by Django 2.1.3 on 2019-02-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0049_auto_20190121_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='regmun',
            name='pop_km2',
            field=models.FloatField(null=True),
        ),
    ]
