# Generated by Django 2.1.3 on 2019-02-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0050_regmun_pop_km2'),
        ('stemp_abw', '0047_auto_20190122_1326'),
    ]

    operations = [
    ]
