# Generated by Django 2.1.3 on 2019-02-13 15:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0051_merge_20190212_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Powerplant',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('chp', models.TextField(blank=True, null=True)),
                ('com_month', models.FloatField(blank=True, null=True)),
                ('com_year', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('decom_month', models.BigIntegerField(blank=True, null=True)),
                ('decom_year', models.BigIntegerField(blank=True, null=True)),
                ('efficiency', models.FloatField(blank=True, null=True)),
                ('energy_source_level_1', models.TextField(blank=True, null=True)),
                ('energy_source_level_2', models.TextField(blank=True, null=True)),
                ('energy_source_level_3', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('state', models.TextField(blank=True, null=True)),
                ('technology', models.TextField(blank=True, null=True)),
                ('thermal_capacity', models.FloatField(blank=True, null=True)),
                ('coastdat2', models.FloatField(blank=True, null=True)),
                ('capacity_in', models.FloatField(blank=True, null=True)),
                ('federal_state', models.TextField(blank=True, null=True)),
                ('ags', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stemp_abw.RegMun')),
            ],
        ),
    ]
