# Generated by Django 2.1.3 on 2019-02-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0052_feedints_powerplant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OsmPowerGen',
        ),
    ]
