# Generated by Django 2.1.3 on 2019-02-14 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0054_feedints'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunData',
            fields=[
                ('ags', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='stemp_abw.RegMun')),
                ('area', models.FloatField()),
                ('pop_2017', models.FloatField()),
                ('pop_2030', models.FloatField()),
                ('pop_2050', models.FloatField()),
                ('gen_count_wind', models.FloatField(default=0)),
                ('gen_count_pv_roof', models.FloatField(default=0)),
                ('gen_count_pv_ground', models.FloatField(default=0)),
                ('gen_count_hydro', models.FloatField(default=0)),
                ('gen_count_bio', models.FloatField(default=0)),
                ('gen_count_steam_turbine', models.FloatField(default=0)),
                ('gen_count_combined_cycle', models.FloatField(default=0)),
                ('gen_count_sewage_landfill_gas', models.FloatField(default=0)),
                ('gen_capacity_wind', models.FloatField(default=0)),
                ('gen_capacity_pv_roof', models.FloatField(default=0)),
                ('gen_capacity_pv_ground', models.FloatField(default=0)),
                ('gen_capacity_hydro', models.FloatField(default=0)),
                ('gen_capacity_bio', models.FloatField(default=0)),
                ('gen_capacity_steam_turbine', models.FloatField(default=0)),
                ('gen_capacity_combined_cycle', models.FloatField(default=0)),
                ('gen_capacity_sewage_landfill_gas', models.FloatField(default=0)),
                ('gen_el_energy_wind', models.FloatField(default=0)),
                ('gen_el_energy_pv_roof', models.FloatField(default=0)),
                ('gen_el_energy_pv_ground', models.FloatField(default=0)),
                ('gen_el_energy_hydro', models.FloatField(default=0)),
                ('dem_el_energy_hh', models.FloatField()),
                ('dem_el_energy_rca', models.FloatField()),
                ('dem_el_energy_ind', models.FloatField()),
                ('dem_th_energy_hh', models.FloatField()),
                ('dem_th_energy_rca', models.FloatField()),
                ('dem_th_energy_ind', models.FloatField()),
            ],
        ),
    ]
