# Generated by Django 2.1.3 on 2019-02-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0055_mundata'),
    ]

    operations = [
        migrations.AddField(
            model_name='mundata',
            name='pop_2011',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mundata',
            name='pop_2017',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mundata',
            name='pop_2030',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mundata',
            name='pop_2050',
            field=models.FloatField(default=0),
        ),
    ]
