# Generated by Django 2.1.3 on 2019-02-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0057_auto_20190215_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mundata',
            old_name='gen_capacity_pv_roof',
            new_name='gen_capacity_pv_roof_large',
        ),
        migrations.RenameField(
            model_name='mundata',
            old_name='gen_count_pv_roof',
            new_name='gen_capacity_pv_roof_small',
        ),
        migrations.AddField(
            model_name='mundata',
            name='gen_count_pv_roof_large',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mundata',
            name='gen_count_pv_roof_small',
            field=models.FloatField(null=True),
        ),
    ]
