# Generated by Django 2.1.3 on 2019-02-15 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0060_auto_20190215_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandTs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('pv_ground', models.FloatField(blank=True, null=True)),
                ('pv_roof', models.FloatField(blank=True, null=True)),
                ('hydro', models.FloatField(blank=True, null=True)),
                ('wind_sq', models.FloatField(blank=True, null=True)),
                ('wind_fs', models.FloatField(blank=True, null=True)),
                ('ags', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stemp_abw.RegMun')),
            ],
        ),
        migrations.AddField(
            model_name='mundata',
            name='dem_el_capacity_hh',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mundata',
            name='dem_el_capacity_ind',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mundata',
            name='dem_el_capacity_rca',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mundata',
            name='dem_th_capacity_hh',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mundata',
            name='dem_th_capacity_ind',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mundata',
            name='dem_th_capacity_rca',
            field=models.FloatField(null=True),
        ),
    ]
