# Generated by Django 2.1.3 on 2019-02-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0061_auto_20190215_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandts',
            old_name='hydro',
            new_name='el_hh',
        ),
        migrations.RenameField(
            model_name='demandts',
            old_name='pv_ground',
            new_name='el_ind',
        ),
        migrations.RenameField(
            model_name='demandts',
            old_name='pv_roof',
            new_name='el_rca',
        ),
        migrations.RenameField(
            model_name='demandts',
            old_name='wind_fs',
            new_name='th_hh',
        ),
        migrations.RenameField(
            model_name='demandts',
            old_name='wind_sq',
            new_name='th_ind',
        ),
        migrations.AddField(
            model_name='demandts',
            name='th_rca',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
