# Generated by Django 2.1.3 on 2019-02-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0063_auto_20190215_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandts',
            old_name='th_hh',
            new_name='th_hh_efh',
        ),
        migrations.AddField(
            model_name='demandts',
            name='th_hh_mfh',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
