# Generated by Django 2.1.3 on 2019-02-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0064_auto_20190215_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandts',
            name='th_hh_efh_spec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandts',
            name='th_hh_mfh_spec',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
