# Generated by Django 2.1.3 on 2019-02-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0065_auto_20190215_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mundata',
            old_name='dem_el_capacity_hh',
            new_name='dem_el_peak_load_hh',
        ),
        migrations.RenameField(
            model_name='mundata',
            old_name='dem_el_capacity_ind',
            new_name='dem_el_peak_load_ind',
        ),
        migrations.RenameField(
            model_name='mundata',
            old_name='dem_el_capacity_rca',
            new_name='dem_el_peak_load_rca',
        ),
        migrations.RenameField(
            model_name='mundata',
            old_name='dem_th_capacity_hh',
            new_name='dem_th_peak_load_hh',
        ),
        migrations.RenameField(
            model_name='mundata',
            old_name='dem_th_capacity_ind',
            new_name='dem_th_peak_load_ind',
        ),
        migrations.RenameField(
            model_name='mundata',
            old_name='dem_th_capacity_rca',
            new_name='dem_th_peak_load_rca',
        ),
    ]
