# Generated by Django 2.1.3 on 2019-02-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0066_auto_20190216_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='mundata',
            name='dem_th_energy_hh_efh',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mundata',
            name='dem_th_energy_hh_efh_spec',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mundata',
            name='dem_th_energy_hh_mfh',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mundata',
            name='dem_th_energy_hh_mfh_spec',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mundata',
            name='dem_th_energy_hh_per_capita',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mundata',
            name='dem_th_energy_total_per_capita',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mundata',
            name='total_living_space',
            field=models.FloatField(null=True),
        ),
    ]
