# Generated by Django 2.1.3 on 2019-02-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0068_regmunstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegMunPopDensity',
        ),
    ]
