# Generated by Django 2.1.3 on 2019-02-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0069_delete_regmunpopdensity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regmun',
            name='pop_km2',
        ),
    ]
