# Generated by Django 2.1.3 on 2019-02-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemp_abw', '0070_remove_regmun_pop_km2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HvMvSubst',
        ),
    ]
